import CHARS from "./data/chars.js";

export const Chaos = [
  [CHARS.ZH.LEVEL_1 + CHARS.ZH.LEVEL_2 + CHARS.ZH.LEVEL_3, CHARS.ZH.TOP_1000],
  [CHARS.EN.VOWELS_UPPER],
  [CHARS.EN.VOWELS_LOWER],
  [CHARS.EN.CONSONANTS_UPPER],
  [CHARS.EN.CONSONANTS_LOWER],
  [CHARS.JP.HIRAGANA],
  [CHARS.JP.KATAKANA],
  [CHARS.GREEK.UPPER],
  [CHARS.GREEK.LOWER],
  [CHARS.NUMBERS.ARABIC],
  [CHARS.NUMBERS.ROMAN_UPPER],
  [CHARS.NUMBERS.ROMAN_LOWER],
];

export const KFC = [
  [CHARS.ZH.LEVEL_1 + CHARS.ZH.LEVEL_2 + CHARS.ZH.LEVEL_3, "K肯德基肯德基疯狂星期四我瘋亂狂星期四我肯德基肯德基疯狂星期四我瘋亂狂星期四我"],
  [CHARS.EN.UPPER, "KFCKFCKV50"],
  [CHARS.EN.LOWER, "KFCKFCKV50"],
  [CHARS.NUMBERS.ARABIC, "500"],
];

export const FURRY = [
  [CHARS.ZH.LEVEL_1 + CHARS.ZH.LEVEL_2 + CHARS.ZH.LEVEL_3, "喵呜汪嗷喵呜汪嗷喵嗚哦咩~ω☆★♡♥"],
  [CHARS.EN.UPPER, "AWOUOMWFF"],
  [CHARS.EN.LOWER, "ouomωhfry"],
  [CHARS.NUMBERS.ARABIC, "114514"],
];

export const KunJinKao = [
  [CHARS.ZH.LEVEL_1 + CHARS.ZH.LEVEL_2 + CHARS.ZH.LEVEL_3, "锟斤拷烫囤"],
  [CHARS.EN.VOWELS_UPPER, CHARS.SPECIAL.BOX],
  [CHARS.EN.VOWELS_LOWER, CHARS.SPECIAL.BOX],
  [CHARS.EN.CONSONANTS_UPPER],
  [CHARS.EN.CONSONANTS_LOWER],
  [CHARS.NUMBERS.ARABIC],
];

export const JP = [
  [CHARS.ZH.LEVEL_1, CHARS.JP.HIRAGANA],
  [CHARS.EN.UPPER, CHARS.JP.KATAKANA],
  [CHARS.EN.LOWER, CHARS.JP.KATAKANA],
  [CHARS.JP.HIRAGANA],
  [CHARS.JP.KATAKANA],
];

export const EN = [
  [CHARS.ZH.LEVEL_1 + CHARS.ZH.LEVEL_2 + CHARS.ZH.LEVEL_3, CHARS.EN.UPPER],
  [CHARS.EN.VOWELS_UPPER],
  [CHARS.EN.VOWELS_LOWER, CHARS.EN.VOWELS_UPPER],
  [CHARS.EN.CONSONANTS_UPPER],
  [CHARS.EN.CONSONANTS_LOWER, CHARS.EN.CONSONANTS_UPPER],
  [CHARS.JP.HIRAGANA, CHARS.EN.UPPER],
  [CHARS.JP.KATAKANA, CHARS.EN.UPPER],
  [CHARS.NUMBERS.ARABIC],
];

export const GREEK = [
  [CHARS.ZH.LEVEL_1 + CHARS.ZH.LEVEL_2 + CHARS.ZH.LEVEL_3, CHARS.GREEK.UPPER + CHARS.GREEK.LOWER + CHARS.EN.UPPER + EN.LOWER],
  [CHARS.EN.UPPER, CHARS.GREEK.UPPER + CHARS.EN.UPPER],
  [CHARS.EN.LOWER, CHARS.GREEK.LOWER + CHARS.EN.LOWER],
  [CHARS.JP.HIRAGANA, CHARS.GREEK.UPPER],
  [CHARS.JP.KATAKANA, CHARS.GREEK.UPPER],
  [CHARS.NUMBERS.ARABIC],
];
